/* Generated by tools/generate_expression_assets.py. Do not hand-edit. */
#ifndef APP_HSHH_EXPRESSION_ASSETS_H
#define APP_HSHH_EXPRESSION_ASSETS_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define APP_HSHH_EXPRESSION_ASSET_COUNT 9u
#define APP_HSHH_EXPRESSION_FRAME_COUNT 5u
#define APP_HSHH_EXPRESSION_WIDTH 320u
#define APP_HSHH_EXPRESSION_HEIGHT 240u

typedef struct {
    const uint8_t *data;
    uint32_t length;
    uint32_t crc32;
} app_hshh_expression_asset_t;

const app_hshh_expression_asset_t *app_hshh_expression_asset_get(uint8_t expression,
                                                                  uint8_t frame);
const char *app_hshh_expression_asset_name(uint8_t expression);
const char *app_hshh_expression_manifest_sha256(void);

#ifdef __cplusplus
}
#endif

#endif /* APP_HSHH_EXPRESSION_ASSETS_H */
