#!/usr/bin/env python3
"""Build deterministic, checksum-addressed T5 expression assets.

The source of truth stays in assets/expressions as PNG.  Firmware embeds small
JPEG frames and decodes one frame at a time into PSRAM, keeping the full 9 x 5
RGB565 set out of SRAM.
"""

from __future__ import annotations

import hashlib
import io
import textwrap
import zlib
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
ASSET_ROOT = ROOT / "assets" / "expressions"
HEADER_PATH = ROOT / "source" / "embedded" / "include" / "app_hshh_expression_assets.h"
SOURCE_PATH = ROOT / "source" / "embedded" / "src" / "app_hshh_expression_assets.c"

EXPRESSIONS = (
    "idle",
    "noticed",
    "listening",
    "thinking",
    "happy",
    "confused",
    "sad",
    "sleeping",
    "angry",
)
FRAME_COUNT = 5
OUTPUT_SIZE = (320, 240)
BACKGROUND = (5, 31, 35)


def _jpeg_bytes(path: Path) -> bytes:
    with Image.open(path) as source:
        rgba = ImageOps.fit(source.convert("RGBA"), OUTPUT_SIZE, Image.Resampling.LANCZOS)
        background = Image.new("RGBA", OUTPUT_SIZE, BACKGROUND + (255,))
        rgb = Image.alpha_composite(background, rgba).convert("RGB")
        output = io.BytesIO()
        rgb.save(output, format="JPEG", quality=88, optimize=True, progressive=False)
        return output.getvalue()


def _c_bytes(data: bytes) -> str:
    values = [f"0x{byte:02x}" for byte in data]
    return "\n".join("    " + ", ".join(values[index : index + 16]) + "," for index in range(0, len(values), 16))


def main() -> None:
    frames: list[tuple[int, int, str, bytes, int]] = []
    manifest = hashlib.sha256()

    for expression_index, expression in enumerate(EXPRESSIONS):
        for frame_index in range(FRAME_COUNT):
            source = ASSET_ROOT / expression / f"{expression}_{frame_index + 1:02d}.png"
            if not source.is_file():
                raise SystemExit(f"missing expression frame: {source}")
            jpeg = _jpeg_bytes(source)
            crc32 = zlib.crc32(jpeg) & 0xFFFFFFFF
            manifest.update(expression.encode("ascii"))
            manifest.update(bytes((frame_index,)))
            manifest.update(len(jpeg).to_bytes(4, "big"))
            manifest.update(crc32.to_bytes(4, "big"))
            frames.append((expression_index, frame_index, f"s_{expression}_{frame_index + 1:02d}", jpeg, crc32))

    header = textwrap.dedent(
        """\
        /* Generated by tools/generate_expression_assets.py. Do not hand-edit. */
        #ifndef APP_HSHH_EXPRESSION_ASSETS_H
        #define APP_HSHH_EXPRESSION_ASSETS_H

        #include <stdint.h>

        #ifdef __cplusplus
        extern "C" {
        #endif

        #define APP_HSHH_EXPRESSION_ASSET_COUNT 9u
        #define APP_HSHH_EXPRESSION_FRAME_COUNT 5u
        #define APP_HSHH_EXPRESSION_WIDTH 320u
        #define APP_HSHH_EXPRESSION_HEIGHT 240u

        typedef struct {
            const uint8_t *data;
            uint32_t length;
            uint32_t crc32;
        } app_hshh_expression_asset_t;

        const app_hshh_expression_asset_t *app_hshh_expression_asset_get(uint8_t expression,
                                                                          uint8_t frame);
        const char *app_hshh_expression_asset_name(uint8_t expression);
        const char *app_hshh_expression_manifest_sha256(void);

        #ifdef __cplusplus
        }
        #endif

        #endif /* APP_HSHH_EXPRESSION_ASSETS_H */
        """
    )

    source_parts = [
        "/* Generated by tools/generate_expression_assets.py. Do not hand-edit. */\n",
        '#include "app_hshh_expression_assets.h"\n\n',
        "#include <stddef.h>\n\n",
    ]
    for _, _, symbol, jpeg, _ in frames:
        source_parts.append(f"static const uint8_t {symbol}[] = {{\n{_c_bytes(jpeg)}\n}};\n\n")

    source_parts.append("static const app_hshh_expression_asset_t s_assets[9][5] = {\n")
    for expression_index, expression in enumerate(EXPRESSIONS):
        source_parts.append(f"    /* {expression} */ {{\n")
        for frame_index in range(FRAME_COUNT):
            _, _, symbol, jpeg, crc32 = frames[expression_index * FRAME_COUNT + frame_index]
            source_parts.append(
                f"        {{{symbol}, (uint32_t)sizeof({symbol}), 0x{crc32:08x}u}},\n"
            )
        source_parts.append("    },\n")
    source_parts.append("};\n\n")
    names = ", ".join(f'"{name}"' for name in EXPRESSIONS)
    source_parts.append(f"static const char *s_names[9] = {{{names}}};\n")
    source_parts.append(f'static const char s_manifest_sha256[] = "{manifest.hexdigest()}";\n\n')
    source_parts.append(
        textwrap.dedent(
            """\
            const app_hshh_expression_asset_t *app_hshh_expression_asset_get(uint8_t expression,
                                                                              uint8_t frame)
            {
                if (expression >= APP_HSHH_EXPRESSION_ASSET_COUNT ||
                    frame >= APP_HSHH_EXPRESSION_FRAME_COUNT) {
                    return NULL;
                }
                return &s_assets[expression][frame];
            }

            const char *app_hshh_expression_asset_name(uint8_t expression)
            {
                return expression < APP_HSHH_EXPRESSION_ASSET_COUNT ? s_names[expression] : "unknown";
            }

            const char *app_hshh_expression_manifest_sha256(void)
            {
                return s_manifest_sha256;
            }
            """
        )
    )

    HEADER_PATH.write_text(header, encoding="utf-8")
    SOURCE_PATH.write_text("".join(source_parts), encoding="utf-8")
    total = sum(len(frame[3]) for frame in frames)
    print(f"generated {len(frames)} frames, {total} bytes, manifest {manifest.hexdigest()}")


if __name__ == "__main__":
    main()
